apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.subdomain | default .Release.Namespace }}.{{ .Values.ingress.domain }}
      secretName: {{ .Values.ingress.secretName | default .Chart.Name }}
  rules:
    - host: {{ .Values.ingress.subdomain | default .Release.Namespace }}.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ .Values.ingress.backend.serviceName }}
              servicePort: {{ .Values.ingress.backend.servicePort }}
