apiVersion: v1
kind: Secret
metadata:
  name: gitlab-token #{{ .Values.initSecretName }}
type: Opaque
data:
  GITLAB_TOKEN: {{ default "TBD" .Values.secrets.gitlabToken | b64enc | quote }}
  JWT_SECRET: {{ default "TBD" .Values.secrets.jwtSecret | b64enc | quote }}
 
